import Link from "next/link";
import { duplicateScheduleAction, toggleScheduleAction } from "@/app/(dashboard)/jornadas/actions";
import { PageHeader } from "@/components/layout/page-header";
import { newScheduleRoute, scheduleRoute } from "@/lib/routes";
import { formatMinutes } from "@/lib/dates/business";
import { getScheduleFormErrorMessage } from "@/lib/presentation/labels";
import { requireActiveProfile } from "@/modules/auth/server/session";
import { listScheduleTemplates } from "@/modules/schedules/application/queries";

export default async function SchedulesPage({ searchParams }: { searchParams: Promise<{ sucesso?: string; erro?: string }> }) {
  const [schedules, profile, query] = await Promise.all([listScheduleTemplates(), requireActiveProfile(), searchParams]);
  const canManage = profile.role === "RH_ADMIN";
  const errorMessage = getScheduleFormErrorMessage(query.erro);
  return <><div className="flex flex-wrap items-start justify-between gap-4"><PageHeader title="Jornadas" description="Modelos de horário, regras por dia e vínculos com vigência histórica." />{canManage ? <Link className="rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white" href={newScheduleRoute}>Nova jornada</Link> : null}</div>{query.sucesso ? <p role="status" className="mb-4 rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">{query.sucesso}</p> : null}{errorMessage ? <p role="alert" className="mb-4 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-900">{errorMessage}</p> : null}{schedules.length === 0 ? <p className="rounded-lg border bg-white p-6 text-sm text-[var(--muted-foreground)]">Nenhuma jornada cadastrada. A aplicação não cria jornadas a partir das marcações.</p> : <div className="grid gap-4 md:grid-cols-2">{schedules.map((schedule) => { const workingDays = schedule.days.filter((day) => day.isWorkingDay); const weeklyMinutes = workingDays.reduce((total, day) => total + day.expectedMinutes, 0); return <article className="rounded-lg border bg-white p-5" key={schedule.id}><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{schedule.name}</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">{schedule.description ?? "Sem descrição"}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{schedule.active ? "Ativa" : "Inativa"}</span></div><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-3"><div><dt className="text-xs uppercase text-[var(--muted-foreground)]">Dias trabalhados</dt><dd>{workingDays.length}</dd></div><div><dt className="text-xs uppercase text-[var(--muted-foreground)]">Carga semanal</dt><dd>{formatMinutes(weeklyMinutes)}</dd></div><div><dt className="text-xs uppercase text-[var(--muted-foreground)]">Vínculos</dt><dd>{schedule._count.assignments}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2"><Link className="rounded-md border px-3 py-2 text-sm font-semibold" href={scheduleRoute(schedule.id)}>Visualizar e editar</Link>{canManage ? <><form action={duplicateScheduleAction}><input type="hidden" name="id" value={schedule.id} /><button className="rounded-md border px-3 py-2 text-sm font-semibold" type="submit">Duplicar</button></form><form action={toggleScheduleAction} className="flex gap-2"><input type="hidden" name="id" value={schedule.id} /><input type="hidden" name="active" value={String(!schedule.active)} />{!schedule.active ? null : <input className="input w-36" name="reason" placeholder="Motivo" />}<button className="rounded-md border px-3 py-2 text-sm font-semibold" type="submit">{schedule.active ? "Inativar" : "Ativar"}</button></form></> : null}</div></article>; })}</div>}</>;
}
