"use client";

import { useFormStatus } from "react-dom";
import { LoadingButton } from "@/components/ui/async-feedback";

type ServerAction = (formData: FormData) => void | Promise<void>;
type NamedOption = { id: string; name: string };

export function ProfessionalDeviceLinkForm({ action, employeeId, devices }: { action: ServerAction; employeeId: string; devices: NamedOption[] }) {
  return <form action={action} className="grid gap-3 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-2"><h2 className="md:col-span-2 text-lg font-semibold">Adicionar vínculo com o relógio</h2><input name="employeeId" type="hidden" value={employeeId} /><label className="grid gap-1 text-sm font-medium">Dispositivo<select className="input" name="deviceId"><option value="">Selecione</option>{devices.map((device) => <option key={device.id} value={device.id}>{device.name}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Código no relógio<input className="input" name="externalEmployeeNumber" /></label><label className="grid gap-1 text-sm font-medium">Início<input className="input" name="validFrom" type="date" /></label><OperationHint steps={["Validando vínculo…", "Salvando vínculo…", "Atualizando o registro do ponto…"]} /><LoadingButton loadingLabel="Salvando vínculo…">Salvar vínculo</LoadingButton></form>;
}

export function EmploymentPolicyForm({ action, employeeId, employmentType, policies, outlined = false }: { action: ServerAction; employeeId: string; employmentType: string; policies: NamedOption[]; outlined?: boolean }) {
  return <details className="rounded-xl border bg-white p-5 shadow-sm"><summary className="cursor-pointer text-sm font-semibold text-[var(--primary)]">Alterar vínculo ou política de cálculo</summary><form action={action} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3"><input name="employeeId" type="hidden" value={employeeId} /><label className="grid gap-1 text-sm font-medium">Tipo de vínculo<select className="input" defaultValue={employmentType} name="employmentType"><option value="EMPLOYEE">CLT/Funcionário</option><option value="INTERN">Estagiário</option><option value="APPRENTICE">Jovem aprendiz</option><option value="CONTRACTOR">PJ/Prestador</option><option value="OTHER">Outro</option></select></label><label className="grid gap-1 text-sm font-medium">Política<select className="input" name="calculationPolicyId"><option value="">Selecione</option>{policies.map((policy) => <option key={policy.id} value={policy.id}>{policy.name}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Início<input className="input" name="validFrom" type="date" /></label><label className="grid gap-1 text-sm font-medium">Fim (opcional)<input className="input" name="validUntil" type="date" /></label><label className="grid gap-1 text-sm font-medium md:col-span-2">Motivo<input className="input" name="reason" placeholder="Ex.: alteração contratual confirmada pelo RH" /></label><label className="flex items-center gap-2 text-sm"><input name="closePrevious" type="checkbox" />Encerrar vínculo anterior</label><label className="flex items-center gap-2 text-sm"><input name="retroactiveConfirmed" type="checkbox" />Confirmo a alteração retroativa</label><OperationHint steps={["Validando período…", "Salvando vínculo e política…", "Recalculando o período afetado…"]} /><LoadingButton className={outlined ? "border bg-white text-slate-900 hover:bg-slate-50" : undefined} loadingLabel="Salvando vínculo…">Salvar vínculo e política</LoadingButton></form></details>;
}

export function ScheduleAssignmentForm({ action, employeeId, schedules, currentScheduleName }: { action: ServerAction; employeeId: string; schedules: NamedOption[]; currentScheduleName?: string }) {
  return <form action={action} className="grid gap-3 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-2 xl:grid-cols-3"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--primary)] md:col-span-2 xl:col-span-3">Alterar configuração</p><h2 className="md:col-span-2 xl:col-span-3 text-lg font-semibold">Trocar modelo de horário</h2><p className="md:col-span-2 xl:col-span-3 text-sm text-[var(--muted-foreground)]">A nova vigência preserva o histórico. Se o recálculo falhar, a atribuição continua salva e pode ser tentada novamente.</p><input name="employeeId" type="hidden" value={employeeId} /><label className="grid gap-1 text-sm font-medium">Novo modelo<select className="input" name="scheduleTemplateId"><option value="">Selecione</option>{schedules.map((schedule) => <option key={schedule.id} value={schedule.id}>{schedule.name}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Início da vigência<input className="input" name="validFrom" type="date" /></label><label className="grid gap-1 text-sm font-medium">Fim (opcional)<input className="input" name="validUntil" type="date" /></label><label className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-sm"><input name="closePrevious" type="checkbox" />Encerrar o modelo atual no dia anterior</label><label className="flex items-center gap-2 text-sm"><input name="retroactiveConfirmed" type="checkbox" />Confirmo a alteração retroativa</label><label className="flex items-center gap-2 text-sm"><input defaultChecked name="recalculate" type="checkbox" />Solicitar recálculo dos dias afetados</label><label className="grid gap-1 text-sm font-medium">Recálculo até<input className="input" name="recalculateUntil" type="date" /></label><label className="grid gap-1 text-sm font-medium md:col-span-2">Motivo<input className="input" name="reason" placeholder="Ex.: horário da manhã confirmado pelo RH" /></label><div className="rounded-lg bg-orange-50 p-3 text-sm text-orange-950 md:col-span-2 xl:col-span-3"><p className="font-semibold">Impacto previsto</p><p className="mt-1">Modelo anterior: {currentScheduleName ?? "nenhum"}. Meses fechados e dias sem cobertura continuam protegidos.</p></div><OperationHint steps={["Validando período…", "Salvando modelo de horário…", "Recalculando registros…"]} /><LoadingButton loadingLabel="Salvando modelo e recalculando…">Salvar modelo e solicitar recálculo</LoadingButton></form>;
}

export function EmployeeRecalculationForm({ action, employeeId }: { action: ServerAction; employeeId: string }) {
  return <form action={action} className="grid gap-3 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-3"><h2 className="md:col-span-3 text-lg font-semibold">Recalcular período</h2><input name="employeeId" type="hidden" value={employeeId} /><label className="grid gap-1 text-sm font-medium">Data inicial<input className="input" name="validFrom" type="date" /></label><label className="grid gap-1 text-sm font-medium">Data final<input className="input" name="validUntil" type="date" /></label><label className="grid gap-1 text-sm font-medium">Motivo<input className="input" name="reason" /></label><OperationHint steps={["Validando período…", "Recalculando registros…", "Atualizando saldos e pendências…"]} /><LoadingButton loadingLabel="Recalculando registros…">Prévia e recálculo controlado</LoadingButton></form>;
}

export function EmployeeMobileAccessForm({ action, employeeId, units, access }: { action: ServerAction; employeeId: string; units: NamedOption[]; access?: { active: boolean; profile: { authUserId: string; email: string }; allowedUnitId: string } | null }) {
  return <form action={action} className="grid gap-3 rounded-xl border bg-white p-5 shadow-sm md:grid-cols-2"><div className="md:col-span-2"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--primary)]">Piloto Golden</p><h2 className="mt-1 text-lg font-semibold">Registro pelo celular</h2><p className="mt-1 text-sm text-[var(--muted-foreground)]">Vincule um usuário já criado no Supabase Auth, defina um PIN inicial e habilite explicitamente esta pessoa. O PIN nunca é exibido nem salvo em texto puro.</p></div><input name="employeeId" type="hidden" value={employeeId} /><label className="grid gap-1 text-sm font-medium">ID do usuário autenticado<input className="input font-mono text-xs" defaultValue={access?.profile.authUserId ?? ""} name="authUserId" placeholder="UUID do Supabase Auth" required /></label><label className="grid gap-1 text-sm font-medium">Unidade autorizada<select className="input" defaultValue={access?.allowedUnitId ?? ""} name="allowedUnitId" required><option value="">Selecione</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">PIN inicial ou novo PIN<input autoComplete="new-password" className="input" inputMode="numeric" maxLength={6} name="pin" pattern="[0-9]{6}" required type="password" /></label><label className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-sm font-medium"><input defaultChecked={access?.active ?? true} name="active" type="checkbox" />Registro pelo celular ativado</label>{access ? <p className="text-sm text-[var(--muted-foreground)]">Usuário vinculado: {access.profile.email}</p> : null}<LoadingButton loadingLabel="Salvando acesso…">Salvar acesso mobile</LoadingButton></form>;
}

function OperationHint({ steps }: { steps: string[] }) {
  const { pending } = useFormStatus();
  return pending ? <p aria-live="polite" className="rounded-lg bg-orange-50 p-3 text-sm text-orange-950" role="status">{steps.join(" ")}</p> : null;
}
