import type { EngineCalculationPolicy } from "@/modules/calculations/domain/calculation-engine";

type DefaultPolicy = Omit<EngineCalculationPolicy, "id"> & { key: string; description: string };

export const defaultCalculationPolicies: readonly DefaultPolicy[] = [
  { key: "clt-standard", name: "CLT padrão", description: "Jornada prevista, atraso, saída antecipada e excedente pendente de aprovação.", requiresSchedule: true, calculateLateArrival: true, calculateEarlyDeparture: true, calculateAbsence: true, calculateNegativeBalance: true, calculateExcessTime: true, excessRequiresApproval: true, requiresBreak: true, shortBreakGeneratesCredit: false, longBreakGeneratesDebit: true, allowAutomaticPositiveBalance: false, attendanceOnly: false, flexibleSchedule: false, duplicateWindowMinutes: 2, entryToleranceMinutes: 5, exitToleranceMinutes: 5, breakToleranceMinutes: 0, toleranceMode: "FULL_EVENT", entryToleranceMode: "FULL_DELAY_AFTER_TOLERANCE" },
  { key: "intern-scheduled", name: "Estágio com jornada", description: "Jornada de estágio com tratamento explícito de horários e intervalo.", requiresSchedule: true, calculateLateArrival: true, calculateEarlyDeparture: true, calculateAbsence: true, calculateNegativeBalance: true, calculateExcessTime: true, excessRequiresApproval: true, requiresBreak: false, shortBreakGeneratesCredit: false, longBreakGeneratesDebit: true, allowAutomaticPositiveBalance: false, attendanceOnly: false, flexibleSchedule: false, duplicateWindowMinutes: 2, entryToleranceMinutes: 5, exitToleranceMinutes: 5, breakToleranceMinutes: 0, toleranceMode: "FULL_EVENT", entryToleranceMode: "FULL_DELAY_AFTER_TOLERANCE" },
  { key: "contractor-scheduled", name: "PJ com jornada", description: "Prestador com jornada acordada; excedente não é aprovado automaticamente.", requiresSchedule: true, calculateLateArrival: true, calculateEarlyDeparture: true, calculateAbsence: true, calculateNegativeBalance: false, calculateExcessTime: true, excessRequiresApproval: true, requiresBreak: false, shortBreakGeneratesCredit: false, longBreakGeneratesDebit: false, allowAutomaticPositiveBalance: false, attendanceOnly: false, flexibleSchedule: false, duplicateWindowMinutes: 2, entryToleranceMinutes: 0, exitToleranceMinutes: 0, breakToleranceMinutes: 0, toleranceMode: "EXCESS_ONLY", entryToleranceMode: "EXCESS_ONLY_AFTER_TOLERANCE" },
  { key: "contractor-flexible", name: "PJ flexível", description: "Exibe horas realizadas sem transformar automaticamente diferenças em saldo.", requiresSchedule: false, calculateLateArrival: false, calculateEarlyDeparture: false, calculateAbsence: false, calculateNegativeBalance: false, calculateExcessTime: false, excessRequiresApproval: true, requiresBreak: false, shortBreakGeneratesCredit: false, longBreakGeneratesDebit: false, allowAutomaticPositiveBalance: false, attendanceOnly: false, flexibleSchedule: true, duplicateWindowMinutes: 2, entryToleranceMinutes: 0, exitToleranceMinutes: 0, breakToleranceMinutes: 0, toleranceMode: "IGNORE_WITHIN_TOLERANCE", entryToleranceMode: "FULL_DELAY_AFTER_TOLERANCE" },
  { key: "contractor-hourly", name: "Prestador por horas", description: "Registra horas realizadas; carga contratual só é comparada quando uma jornada for atribuída.", requiresSchedule: false, calculateLateArrival: false, calculateEarlyDeparture: false, calculateAbsence: false, calculateNegativeBalance: false, calculateExcessTime: false, excessRequiresApproval: true, requiresBreak: false, shortBreakGeneratesCredit: false, longBreakGeneratesDebit: false, allowAutomaticPositiveBalance: false, attendanceOnly: false, flexibleSchedule: true, duplicateWindowMinutes: 2, entryToleranceMinutes: 0, exitToleranceMinutes: 0, breakToleranceMinutes: 0, toleranceMode: "IGNORE_WITHIN_TOLERANCE", entryToleranceMode: "FULL_DELAY_AFTER_TOLERANCE" },
  { key: "attendance-only", name: "Somente presença", description: "Registra presença e horas, sem saldo positivo, negativo ou ausência automática.", requiresSchedule: false, calculateLateArrival: false, calculateEarlyDeparture: false, calculateAbsence: false, calculateNegativeBalance: false, calculateExcessTime: false, excessRequiresApproval: true, requiresBreak: false, shortBreakGeneratesCredit: false, longBreakGeneratesDebit: false, allowAutomaticPositiveBalance: false, attendanceOnly: true, flexibleSchedule: true, duplicateWindowMinutes: 2, entryToleranceMinutes: 0, exitToleranceMinutes: 0, breakToleranceMinutes: 0, toleranceMode: "IGNORE_WITHIN_TOLERANCE", entryToleranceMode: "FULL_DELAY_AFTER_TOLERANCE" },
];
