"use client";

import { useState } from "react";

type AdjustmentChoice = "MISSING_PUNCH" | "INVALID_PUNCH" | "JUSTIFIED_ABSENCE" | "MEDICAL_CERTIFICATE" | "EXTERNAL_WORK" | "EXCESS_APPROVAL" | "HOURS_CREDIT" | "HOURS_DEBIT" | "SCHEDULE_CORRECTION";

const choices: Array<{ value: AdjustmentChoice; label: string }> = [
  { value: "MISSING_PUNCH", label: "Adicionar marcação esquecida" }, { value: "INVALID_PUNCH", label: "Desconsiderar marcação incorreta" }, { value: "JUSTIFIED_ABSENCE", label: "Justificar ausência" }, { value: "MEDICAL_CERTIFICATE", label: "Registrar atestado" }, { value: "EXTERNAL_WORK", label: "Registrar trabalho externo" }, { value: "EXCESS_APPROVAL", label: "Aprovar tempo excedente" }, { value: "HOURS_CREDIT", label: "Adicionar crédito de horas" }, { value: "HOURS_DEBIT", label: "Adicionar débito de horas" }, { value: "SCHEDULE_CORRECTION", label: "Corrigir jornada do dia" },
];

export function AdjustmentForm({ action, summaryId, employeeId, date, punches }: { action: (formData: FormData) => void | Promise<void>; summaryId: string; employeeId: string; date: string; punches: Array<{ id: string; label: string }> }) {
  const [choice, setChoice] = useState<AdjustmentChoice>("MISSING_PUNCH");
  const [hours, setHours] = useState("0");
  const [minutes, setMinutes] = useState("0");
  const duration = Math.max(0, Number(hours) * 60 + Number(minutes));
  const usesDuration = ["EXCESS_APPROVAL", "HOURS_CREDIT", "HOURS_DEBIT"].includes(choice);
  const needsPunch = choice === "INVALID_PUNCH";
  return <form action={action} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input type="hidden" name="summaryId" value={summaryId} /><input type="hidden" name="employeeId" value={employeeId} /><input type="hidden" name="date" value={date} /><input type="hidden" name="type" value={choice === "INVALID_PUNCH" ? "INVALID_PUNCH" : choice} /><input type="hidden" name="minutesCredited" value={choice === "HOURS_CREDIT" || choice === "EXCESS_APPROVAL" ? duration : 0} /><input type="hidden" name="minutesDebited" value={choice === "HOURS_DEBIT" ? duration : 0} /><label className="grid gap-1 text-sm md:col-span-2 xl:col-span-4">O que deseja corrigir?<select className="input" value={choice} onChange={(event) => setChoice(event.target.value as AdjustmentChoice)}>{choices.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>{choice === "MISSING_PUNCH" ? <><label className="grid gap-1 text-sm">Tipo da marcação<select className="input" name="adjustedPunchCode" defaultValue="S"><option value="S">Entrada</option><option value="E">Saída para intervalo</option><option value="A">Retorno do intervalo</option><option value="F">Saída final</option></select></label><label className="grid gap-1 text-sm">Horário<input className="input" type="time" name="adjustedTime" required /></label></> : null}{needsPunch ? <label className="grid gap-1 text-sm md:col-span-2">Marcação a desconsiderar<select className="input" name="originalPunchId" required><option value="">Selecione</option>{punches.map((punch) => <option key={punch.id} value={punch.id}>{punch.label}</option>)}</select></label> : null}{usesDuration ? <><label className="grid gap-1 text-sm">Horas<input className="input" min="0" max="24" type="number" value={hours} onChange={(event) => setHours(event.target.value)} /></label><label className="grid gap-1 text-sm">Minutos<input className="input" min="0" max="59" type="number" value={minutes} onChange={(event) => setMinutes(event.target.value)} /></label><p className="self-end text-sm text-[var(--muted-foreground)]">Duração informada: <strong>{hours}h{minutes.padStart(2, "0")}</strong></p></> : null}<label className="grid gap-1 text-sm md:col-span-2">Justificativa<input className="input" name="reason" required minLength={3} placeholder="Explique brevemente a correção" /></label><button className="rounded-md bg-[var(--primary)] px-4 py-2 text-sm font-semibold text-white" type="submit">Salvar ajuste e recalcular</button></form>;
}
