import { NextResponse } from "next/server";
import { MobileAttendanceError } from "@/modules/mobile-attendance/application/errors";
import { mobilePunchSupportCode, registerMobilePunch } from "@/modules/mobile-attendance/application/mobile-attendance-service";

export const runtime = "nodejs";

function supportCodeForPayload(payload: unknown) {
  if (!payload || typeof payload !== "object" || !("requestId" in payload)) return undefined;
  const requestId = payload.requestId;
  // Only derive a support reference from the UUID generated by the client.
  // Never echo arbitrary request content in an error response.
  if (typeof requestId !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(requestId)) {
    return undefined;
  }
  return mobilePunchSupportCode(requestId);
}

export async function POST(request: Request) {
  let payload: unknown;
  try {
    payload = await request.json();
    const result = await registerMobilePunch(payload);
    return NextResponse.json({
      receipt: {
        id: result.punch.id,
        registeredAt: result.punch.registeredAt.toISOString(),
        receiptCode: result.punch.receiptCode,
        locationStatus: result.punch.locationStatus,
        reviewRequired: result.punch.reviewRequired,
      },
      duplicate: result.duplicate,
      supportCode: result.supportCode,
    });
  } catch (error) {
    const known = error instanceof MobileAttendanceError;
    const supportCode = known ? error.supportCode ?? supportCodeForPayload(payload) : supportCodeForPayload(payload);
    if (!known) console.error("[mobile-punch]", { code: "UNAVAILABLE", supportCode });
    return NextResponse.json({
      code: known ? error.code : "UNAVAILABLE",
      supportCode,
      // This is enough for a helpful retry instruction, without disclosing
      // coordinates or the unit's allowed radius to the browser.
      locationStatus: known ? error.details?.locationStatus : undefined,
    }, { status: known ? (error.code === "UNAUTHORIZED" ? 401 : 400) : 500 });
  }
}
